### pitstop dataset

build a pitstop dataset across all the oval races

+ gap distribution analysis. (normal pit .vs. pit in caution laps)

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ["CUDA_VISIBLE_DEVICES"]="7"

## Load Data

In [2]:
import os
os.getcwd()

'/scratch/hpda/indycar/predictor/notebook/8.PitStopAnalysis'

In [3]:
#
# parameters
#
#year = '2017'
year = '2018'
#event = 'Toronto'
#https://www.racing-reference.info/season-stats/2018/O/#
events_totalmiles=[256,500,372,268,500,310]
events_laplen = [1.022,2.5,1.5,0.894,2.5,1.25]
events = ['Phoenix','Indy500','Texas','Iowa','Pocono','Gateway']
#events = ['Indy500']
#events = ['Phoenix']

In [4]:
# make indy car completed_laps dataset
# car_number, completed_laps, rank, elapsed_time, rank_diff, elapsed_time_diff 
def make_cl_data(dataset):

    # pick up data with valid rank
    rankdata = dataset.rename_axis('MyIdx').sort_values(by=['elapsed_time','MyIdx'], ascending=True)
    rankdata = rankdata.drop_duplicates(subset=['car_number', 'completed_laps'], keep='first')

    # resort by car_number, lap
    uni_ds = rankdata.sort_values(by=['car_number', 'completed_laps', 'elapsed_time'], ascending=True)    
    uni_ds = uni_ds.drop(["unique_id", "best_lap", "current_status", "track_status", "lap_status",
                      "laps_behind_leade","laps_behind_prec","overall_rank","pit_stop_count",
                      "last_pitted_lap","start_position","laps_led"], axis=1)
    
    carnumber = set(uni_ds['car_number'])
    print('cars:', carnumber)
    print('#cars=', len(carnumber))
   
    # faster solution , uni_ds already sorted by car_number and lap
    uni_ds['rank_diff'] = uni_ds['rank'].diff()
    mask = uni_ds.car_number != uni_ds.car_number.shift(1)
    uni_ds['rank_diff'][mask] = 0
    
    uni_ds['time_diff'] = uni_ds['elapsed_time'].diff()
    mask = uni_ds.car_number != uni_ds.car_number.shift(1)
    uni_ds['time_diff'][mask] = 0
    
    df = uni_ds[['car_number','completed_laps','rank','elapsed_time','rank_diff','time_diff']]
    
    return df

def make_lapstatus_data(dataset):
    final_lap = max(dataset.completed_laps)
    total_laps = final_lap + 1

    # get records for the cars that finish the race
    completed_car_numbers= dataset[dataset.completed_laps == final_lap].car_number.values
    completed_car_count = len(completed_car_numbers)

    print('count of completed cars:', completed_car_count)
    print('completed cars:', completed_car_numbers)
    
    #pick up one of them
    onecar = dataset[dataset['car_number']==completed_car_numbers[0]]
    onecar = onecar.drop_duplicates(subset=['car_number', 'completed_laps'], keep='first')
    return onecar[['completed_laps','track_status']]

In [5]:
def load_data(event, year):
    inputfile = '../data/final/C_'+ event +'-' + year + '-final.csv'
    outputprefix = year +'-' + event + '-'
    dataset = pd.read_csv(inputfile)
    #dataset.info(verbose=True)    
    
    final_lap = max(dataset.completed_laps)
    total_laps = final_lap + 1

    # get records for the cars that finish the race
    completed_car_numbers= dataset[dataset.completed_laps == final_lap].car_number.values
    completed_car_count = len(completed_car_numbers)

    print('count of completed cars:', completed_car_count)
    print('completed cars:', completed_car_numbers)

    #make a copy
    alldata = dataset.copy()
    dataset = dataset[dataset['car_number'].isin(completed_car_numbers)]
    rankdata = alldata.rename_axis('MyIdx').sort_values(by=['elapsed_time','MyIdx'], ascending=True)
    rankdata = rankdata.drop_duplicates(subset=['car_number', 'completed_laps'], keep='first')
    
    cldata = make_cl_data(dataset)
    flagdata = make_lapstatus_data(dataset)
    acldata = make_cl_data(alldata)

    return alldata, rankdata, acldata, flagdata

### overall view of laptime scatter plots

In [6]:
def get_cardata(curcarno, ycol='time_diff'):
    car = acldata[acldata['car_number']==curcarno]
    #print(car['time_diff'].describe())
    
    cols=['completed_laps','rank','car_number','lap_status','track_status',
    'pit_stop_count','current_status','start_position']
    colid={key:idx for idx, key in enumerate(cols)}

    cardata = rankdata[rankdata['car_number'] == curcarno]

    carstatus = [[row[0], row[1],row[2],row[3],row[4],row[5],row[6],row[7]] for row in cardata[
        ['completed_laps','rank','car_number','lap_status','track_status',
        'pit_stop_count','current_status','start_position']].values]
    
    x = car['completed_laps'][1:].values
    y = car[ycol][1:].values

    pits=[]
    yellowflags=[]
    lastflag = 'x'
    for row in carstatus:
        lap = int(row[colid['completed_laps']])

        if row[colid['lap_status']]=='P':
            pits.append(lap)

        if row[colid['track_status']]=='Y':
            if lastflag != 'Y':       
                #start
                yellowflags.append(lap)
        else:
            if lastflag == 'Y':       
                #end
                yellowflags.append(lap)        
        lastflag = row[colid['track_status']]

    #pit lap
    pits = np.array(pits)
    #start, end lap
    #
    yellowflags = np.array(yellowflags)
    if (yellowflags.shape[0] % 2)==1:
        print('crash?:carno=', curcarno)
        yellowflags = []
    else:
        yellowflags = np.array(yellowflags).reshape((-1,2))    
    
    return car, x, y, pits, yellowflags

### bulid the dataset

In [7]:
def get_stagedata(TRIM=2):
    """
    input: acldata, rankdata, the whole dataset
    output: stagedata['car_number','stage','start_lap','end_lap','start_rank','end_rank']
    """
    carlist = set(acldata['car_number'])
    data = []
    for curcarno in carlist:
        car = acldata[acldata['car_number']==curcarno]
        #print(car['time_diff'].describe())

        cols=['completed_laps','rank','car_number','lap_status','track_status',
        'pit_stop_count','current_status','start_position']
        colid={key:idx for idx, key in enumerate(cols)}

        cardata = rankdata[rankdata['car_number'] == curcarno]

        carstatus = [[row[0], row[1],row[2],row[3],row[4],row[5],row[6],row[7]] for row in cardata[
            ['completed_laps','rank','car_number','lap_status','track_status',
            'pit_stop_count','current_status','start_position']].values]

        pits=[]
        yellowflags=[]
        lastflag = 'x'
        
        stage = 0
        start_lap = 0
        pit_lap = -1
        pit_in_caution = 0
        for row in carstatus:
            lap = int(row[colid['completed_laps']])
            
            if lap==0:
                #hex2int
                start_rank = int(row[colid['start_position']], 16)     
            
            if row[colid['lap_status']]=='P' and row[colid['current_status']]=='Active':
                pits.append(lap)
                end_lap = lap - TRIM
                end_rank = carstatus[end_lap][colid['rank']]
                
                pit_lap = lap  #current is pit lap
                pit_in_caution = 1 if row[colid['track_status']]=='Y' else 0
                #add one record
                #stagedata['car_number','stage','start_lap','end_lap','start_rank','end_rank']
                data.append([curcarno,stage,start_lap, end_lap, pit_lap, pit_in_caution, start_rank, end_rank])
                # prepare for the next
                stage += 1
                start_lap = end_lap  # end_lap + 1?
                start_rank = end_rank
                

            if row[colid['track_status']]=='Y':
                if lastflag != 'Y':       
                    #start
                    yellowflags.append(lap)
            else:
                if lastflag == 'Y':       
                    #end
                    yellowflags.append(lap)        
            lastflag = row[colid['track_status']]

        #final
        end_lap = carstatus[-1][colid['completed_laps']]
        end_rank = carstatus[-1][colid['rank']]
        #add one record
        #stagedata['car_number','stage','start_lap','end_lap',pit_lap, pit_in_caution,'start_rank','end_rank']
        #data.append([curcarno,stage,start_lap, end_lap, pit_lap, pit_in_caution, start_rank, end_rank])
        
        #pit lap
        pits = np.array(pits)
        #start, end lap
        #
        yellowflags = np.array(yellowflags)
        if (yellowflags.shape[0] % 2)==1:
            print('crash?:carno=', curcarno)
            yellowflags = []
        else:
            yellowflags = np.array(yellowflags).reshape((-1,2))  
            
    data = np.array(data)
    #['car_number','stage','start_lap','end_lap',pit_lap, pit_in_caution,'start_rank','end_rank']
    df = pd.DataFrame({'car_number': data[:, 0], 'stage': data[:, 1],'start_lap': data[:, 2],
                      'end_lap': data[:, 3], 'pit_lap': data[:, 4], 'pit_in_caution': data[:, 5],
                       'start_rank': data[:, 6],'end_rank': data[:, 7]})
    return df, data

### events

In [8]:
def extract_features(stagedata):
    """
    input: (alldata, rankdata, acldata, flagdata, stage, data)
    
    target
    eventid
    car_number
    stageid
    
    #0, gobal info 
    firststage  ;  1/0    
    pit_in_caution; 1/0
    start_position  ; #
    
    # 0 order of #rank
    start_rank  ;  #rank
    start_rank_ratio; ; #rank/carnum 
    top_pack    ;  top5 1/0 
    bottom_pack  ; bottom5 1/0 
    
    average_rank  ; previous stage
    average_rank_all  ; all previous stages
    
    # 1 order of #rank
    change_in_rank; previous stage
    change_in_rank_all;  all previous stages
    # 2 order of #rank
    rate_of_change; previous stage
    rate_of_change_all;  all previous stages
    
    #neighbors;   
    prev_nb0_change_in_rank
    prev_nb1_change_in_rank
    prev_nb2_change_in_rank
    follow_nb0_change_in_rank
    follow_nb1_change_in_rank
    follow_nb2_change_in_rank
    
    """
    eventid = 0
    cols=['target','start_lap',
             'eventid','car_number','stageid',
             'firststage','pit_in_caution','start_position',
             'start_rank','start_rank_ratio','top_pack','bottom_pack',
             'average_rank','average_rank_all',
             'change_in_rank','change_in_rank_all','rate_of_change','rate_of_change_all',
             'prev_nb0_change_in_rank','prev_nb1_change_in_rank','prev_nb2_change_in_rank',
             'follow_nb0_change_in_rank','follow_nb1_change_in_rank','follow_nb2_change_in_rank']
    colid={key:idx for idx, key in enumerate(cols)}
    
    datacols = ['car_number','stage','start_lap','end_lap','pit_lap', 'pit_in_caution', 'start_rank','end_rank']
    datacolid={key:idx for idx, key in enumerate(datacols)}
    
    #maintain a <car,lap, (rank, stage)> index 
    idxcols = ['car_number','completed_laps','rank','stageid']
    carindex = {}
    
    stagedf = pd.DataFrame([],columns=cols)
    for event in stagedata.keys():
        alldata, rankdata, acldata, flagdata, stage, data = stagedata[event]
        carlist = set(acldata['car_number'])
        laplist = set(acldata['completed_laps'])
        totalcars = len(carlist)
        totallaps = len(laplist)

        # init the index
        #carindex[eventid] = np.array((totalcars, totallaps, 2))
        carindex[eventid] = pd.DataFrame([],columns=idxcols)
        
        records = []
        
        laphist = []
        rankhist = []
        rankchghist = []        
        #['car_number','stage','start_lap','end_lap',pit_lap, pit_in_caution, 'start_rank','end_rank']
        for row in data:
            # a new record
            rec={}
            #status, 'start_lap', start a new car
            if row[datacolid['start_lap']] == 0:
                start_position = row[datacolid['start_rank']]
                laphist = []
                rankhist = []
                rankchghist = []
            
            #target 
            rec['target'] = row[datacolid['end_rank']] - row[datacolid['start_rank']]
            rec['start_lap'] = row[datacolid['start_lap']]
            
            #features
            rec['eventid'] = eventid
            rec['car_number'] = row[datacolid['car_number']]
            rec['stageid'] = row[datacolid['stage']]
            rec['firststage'] = 0 if row[datacolid['stage']]==0 else 1
            rec['pit_in_caution'] = row[datacolid['pit_in_caution']]
            rec['start_position'] = start_position
            rec['start_rank'] = row[datacolid['start_rank']]
            rec['start_rank_ratio'] = rec['start_rank'] / totalcars
            rec['top_pack'] = 1 if rec['start_rank']<=5 else 0
            #todo, not accurate here
            rec['bottom_pack'] = 1 if rec['start_rank']>=totalcars-5 else 0
            #get from laphist
            if laphist:
                #previous stage
                prev_stage = laphist[-1]
                rec['average_rank'] = np.mean(list(prev_stage['rank']))
                rec['average_rank_all'] = np.mean(rankhist)
            else:
                rec['average_rank'] = rec['start_rank']
                rec['average_rank_all'] = rec['start_rank']
                
            #change in rank
            if rankchghist:
                rec['change_in_rank'] = rankchghist[-1]
                rec['change_in_rank_all'] = np.mean(rankchghist)
            else:
                rec['change_in_rank'] = 0
                rec['change_in_rank_all'] = 0
                
            #rate of change in rank
            if len(rankchghist)>2:
                rec['rate_of_change'] = rankchghist[-1] - rankchghist[-2]
                rec['rate_of_change_all'] = (rankchghist[-1] - rankchghist[0])/(len(rankchghist)-1)
            else:
                rec['rate_of_change'] = 0
                rec['rate_of_change_all'] = 0            
                
            # init neighbor info as 0
            rec['prev_nb0_change_in_rank'] = 0
            rec['prev_nb1_change_in_rank'] = 0
            rec['prev_nb2_change_in_rank'] = 0
            rec['follow_nb0_change_in_rank'] = 0
            rec['follow_nb1_change_in_rank'] = 0
            rec['follow_nb2_change_in_rank'] = 0
            

                
            
            #add one record
            records.append([rec[col] for col in cols])
            
            #update for the new stage
            lapdata = rankdata[(rankdata['car_number']== rec['car_number']) & 
                               (rankdata['completed_laps']>=row[datacolid['start_lap']]) &
                               (rankdata['completed_laps']<row[datacolid['end_lap']])
                              ]
            laphist.append(lapdata)
            rankhist.extend(list(lapdata['rank']))
            rankchghist.append(row[datacolid['end_rank']] - row[datacolid['start_rank']])
            
            # add to index, go through the lapdata
            #or _lap in range(row[datacolid['start_lap']],row[datacolid['end_lap']]):
            for index, row in lapdata.iterrows():
                #carindex[eventid][rec['car_number'], row['completed_laps'], 0] = row['rank']
                #carindex[eventid][rec['car_number'], row['completed_laps'], 1 = rec['stageid']
                laprec = [rec['car_number'], row['completed_laps'], row['rank'],rec['stageid']]
                df = pd.DataFrame([laprec],columns=idxcols)
                carindex[eventid] = pd.concat([carindex[eventid], df], ignore_index=True)
            
          
        # push this event into stage dataframe
        print('eventid=%d, records=%d'%(eventid, len(records)))
        df = pd.DataFrame(records,columns=cols)
        stagedf = pd.concat([stagedf, df], ignore_index=True)
        
        #for the next new event
        eventid += 1
        
    return stagedf, carindex

def update_neighbor(stagedf, carindex):
    # go through stage data to add neighbor info
    # carindex[eventid] <car, lap, (rank, stage)
    ndf = stagedf.copy()
    
    #stagedf.index = pd.RangeIndex(len(stagedf.index))
        
    for index, row in stagedf.iterrows():
        
        eventid = row['eventid']
        
        currank = row['start_rank']
        curlap = row['start_lap']
        if curlap == 0:
            continue
        
        df = carindex[row['eventid']]
        df_lap = df[df['completed_laps']==curlap]
        prev0 = df_lap[df_lap['rank'] == currank - 1]
        prev1 = df_lap[df_lap['rank'] == currank - 2]
        prev2 = df_lap[df_lap['rank'] == currank - 3]
        follow0 = df_lap[df_lap['rank'] == currank + 1]
        follow1 = df_lap[df_lap['rank'] == currank + 2]
        follow2 = df_lap[df_lap['rank'] == currank + 3]
        
        recs = [prev0, prev1, prev2, follow0, follow1,follow2]
        recloc = ['prev_nb0_change_in_rank','prev_nb1_change_in_rank','prev_nb2_change_in_rank',
                 'follow_nb0_change_in_rank','follow_nb1_change_in_rank','follow_nb2_change_in_rank']
        for recidx, rec in enumerate(recs):
            if rec.empty:
                continue
                
            car_number = rec['car_number']
            stageid = rec['stageid']
            #print('event:%d, car:%d, stage:%d, index:%d'%(eventid, car_number, stageid, index))
            #find the record of prev0 by eventid, carno, stageid
            #neighbor = stagedf[(stagedf['eventid'] == eventid) & (stagedf['car_number'] == car_number) & (stagedf['stageid'] == stageid)]
            #neighbor = ndf[(ndf['eventid'] == eventid) & (ndf['car_number'] == car_number) & (ndf['stageid'] == stageid)]
            neighbor = ndf.query('eventid == %d & car_number==%d & stageid==%d'%(eventid,car_number,stageid))
            
            if neighbor.empty:
                print('error: empty neighbor at: '%(eventid,car_number,stageid))
                continue
            
            # update current row
            #print('index=%d, col=%s'%(index, recloc[recidx]))
            stagedf.loc[index,recloc[recidx]] = neighbor['change_in_rank'].values[0]
            #stagedf.loc[index,recloc[recidx]] = 1
                                
    return stagedf

def extract_stint_features(stagedata):
    """
    input: (alldata, rankdata, acldata, flagdata, stage, data)
    
    lap_distance    ; lap distance for this stint
    eventid
    car_number
    stageid
    
    pit_in_caution; 1/0
    start_position  ; #
    start_rank  ;  #rank
    end_rank
    """
    eventid = 0
    cols=['lap_distance','start_lap','pit_lap',
             'eventid','car_number','stageid',
             'pit_in_caution','start_position',
             'start_rank', 'end_rank']
    colid={key:idx for idx, key in enumerate(cols)}
    
    datacols = ['car_number','stage','start_lap','end_lap','pit_lap', 'pit_in_caution', 'start_rank','end_rank']
    datacolid={key:idx for idx, key in enumerate(datacols)}
    
    #maintain a <car,lap, (rank, stage)> index 
    idxcols = ['car_number','completed_laps','rank','stageid']
    carindex = {}
    
    stagedf = pd.DataFrame([],columns=cols)
    for event in stagedata.keys():
        alldata, rankdata, acldata, flagdata, stage, data = stagedata[event]
        carlist = set(acldata['car_number'])
        laplist = set(acldata['completed_laps'])
        totalcars = len(carlist)
        totallaps = len(laplist)

        # init the index
        #carindex[eventid] = np.array((totalcars, totallaps, 2))
        carindex[eventid] = pd.DataFrame([],columns=idxcols)
        
        records = []
        
        laphist = []
        rankhist = []
        rankchghist = []        
        #['car_number','stage','start_lap','end_lap',pit_lap, pit_in_caution, 'start_rank','end_rank']
        for row in data:
            # a new record
            rec={}
            #status, 'start_lap', start a new car
            if row[datacolid['start_lap']] == 0:
                start_position = row[datacolid['start_rank']]
                laphist = []
                rankhist = []
                rankchghist = []
            
            #target 
            rec['lap_distance'] = row[datacolid['end_lap']] - row[datacolid['start_lap']] + 1
            rec['start_lap'] = row[datacolid['start_lap']]
            rec['pit_lap'] = row[datacolid['pit_lap']]
            
            #features
            rec['eventid'] = eventid
            rec['car_number'] = row[datacolid['car_number']]
            rec['stageid'] = row[datacolid['stage']]
            
            rec['pit_in_caution'] = row[datacolid['pit_in_caution']]
            rec['start_position'] = start_position
            rec['start_rank'] = row[datacolid['start_rank']]
            rec['end_rank'] = row[datacolid['end_rank']]
            
            
            #add one record
            records.append([rec[col] for col in cols])
            
            #update for the new stage
            lapdata = rankdata[(rankdata['car_number']== rec['car_number']) & 
                               (rankdata['completed_laps']>=row[datacolid['start_lap']]) &
                               (rankdata['completed_laps']<row[datacolid['end_lap']])
                              ]
            laphist.append(lapdata)
            rankhist.extend(list(lapdata['rank']))
            rankchghist.append(row[datacolid['end_rank']] - row[datacolid['start_rank']])
            
            # add to index, go through the lapdata
            #or _lap in range(row[datacolid['start_lap']],row[datacolid['end_lap']]):
            for index, row in lapdata.iterrows():
                #carindex[eventid][rec['car_number'], row['completed_laps'], 0] = row['rank']
                #carindex[eventid][rec['car_number'], row['completed_laps'], 1 = rec['stageid']
                laprec = [rec['car_number'], row['completed_laps'], row['rank'],rec['stageid']]
                df = pd.DataFrame([laprec],columns=idxcols)
                carindex[eventid] = pd.concat([carindex[eventid], df], ignore_index=True)
            
          
        # push this event into stage dataframe
        print('eventid=%d, records=%d'%(eventid, len(records)))
        df = pd.DataFrame(records,columns=cols)
        stagedf = pd.concat([stagedf, df], ignore_index=True)
        
        #for the next new event
        eventid += 1
        
    return stagedf, carindex

### load data

In [9]:
stagedata = {}
traindata = None
for event in events:
    #alldata, rankdata, acldata, flagdata
    stagedata[event] = load_data(event, year)
    
    alldata, rankdata, acldata, flagdata = stagedata[event]
    carlist = set(acldata['car_number'])
    laplist = set(acldata['completed_laps'])
    print('%s: carno=%d, lapnum=%d'%(event, len(carlist), len(laplist)))
    
    stage, data = get_stagedata(0)
    stagedata[event] = (alldata, rankdata, acldata, flagdata, stage, data)
    
    if traindata is None:
        traindata = data
    else:
        traindata = np.vstack((traindata, data))

('count of completed cars:', 11)
('completed cars:', array([ 1,  6, 27,  9, 28,  5, 20, 14, 15, 22, 30]))
('cars:', set([1, 5, 6, 9, 14, 15, 20, 22, 27, 28, 30]))
('#cars=', 11)

/scratch/hpda/anaconda3/envs/py2/lib/python2.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/scratch/hpda/anaconda3/envs/py2/lib/python2.7/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

('count of completed cars:', 11)
('completed cars:', array([ 1,  6, 27,  9, 28,  5, 20, 14, 15, 22, 30]))
('cars:', set([1, 4, 5, 6, 9, 10, 12, 14, 15, 18, 19, 20, 21, 22, 23, 26, 27, 28, 30, 32, 59, 88, 98]))
('#cars=', 23)
Phoenix: carno=23, lapnum=251
('crash?:carno=', 10)
('crash?:carno=', 19)

In [10]:
stintdf, carindex = extract_stint_features(stagedata)

eventid=0, records=89

In [11]:
#stagedf0.reset_index(inplace=True)
#stagedf = update_neighbor(stagedf0, carindex)

In [12]:
#stintdf = stintdf.drop(columns=['start_lap'])

In [13]:
stintdf.to_csv('stint-%s.csv'%year)

In [14]:
#rankdata[rankdata['car_number']==12]
#[['completed_laps','last_laptime','track_status']]

,rank,car_number,unique_id,completed_laps,elapsed_time,last_laptime,lap_status,best_laptime,best_lap,time_behind_leader,...,time_behind_prec,laps_behind_prec,overall_rank,overall_best_laptime,current_status,track_status,pit_stop_count,last_pitted_lap,start_position,laps_led
MyIdx,,,,,,,,,,,,,,,,,,,,,
2,3,12,2,0,0.1506,43.5852,T,0.0000,0,0.1506,...,0.0863,0,3,0.0000,Active,G,0,0,3,0
48,3,12,2,1,22.4057,22.2551,T,22.2551,1,1.0430,...,0.5250,0,3,22.2551,Active,G,0,0,3,0
101,4,12,2,2,44.2206,21.8149,T,21.8149,2,2.2309,...,0.6245,0,4,21.8149,Active,G,0,0,3,0
154,4,12,2,3,65.2507,21.0301,T,21.0301,3,2.4663,...,0.9305,0,4,21.0301,Active,G,0,0,3,0
208,4,12,2,4,86.1774,20.9267,T,20.9267,4,2.4706,...,1.1199,0,4,20.9267,Active,G,0,0,3,0
263,4,12,2,5,107.2470,21.0696,T,20.9267,4,2.5757,...,1.3877,0,4,20.9267,Active,G,0,0,3,0
318,4,12,2,6,128.3307,21.0837,T,20.9267,4,2.6254,...,1.7008,0,4,20.9267,Active,G,0,0,3,0
376,4,12,2,7,149.4372,21.1065,T,20.9267,4,2.6351,...,1.7600,0,4,20.9267,Active,G,0,0,3,0
437,4,12,2,8,170.5346,21.0974,T,20.9267,4,2.4404,...,1.6296,0,4,20.9267,Active,G,0,0,3,0
498,4,12,2,9,191.8476,21.3130,T,20.9267,4,2.3838,...,1.5712,0,4,20.9267,Active,G,0,0,3,0
557,4,12,2,10,213.1492,21.3016,T,20.9267,4,2.3153,...,1.3441,0,4,20.9267,Active,G,0,0,3,0
617,4,12,2,11,234.5066,21.3574,T,20.9267,4,2.2706,...,1.1325,0,4,20.9267,Active,G,0,0,3,0
678,4,12,2,12,256.0468,21.5402,T,20.9267,4,2.4029,...,0.9986,0,4,20.9267,Active,G,0,0,3,0
739,4,12,2,13,277.7136,21.6668,T,20.9267,4,2.4800,...,1.2907,0,4,20.9267,Active,G,0,0,3,0
800,4,12,2,14,299.2013,21.4877,T,20.9267,4,1.7620,...,0.9685,0,4,20.9267,Active,G,0,0,3,0
857,4,12,2,15,321.1930,21.9917,T,20.9267,4,1.3889,...,0.6618,0,4,20.9267,Active,G,0,0,3,0
916,4,12,2,16,343.5128,22.3198,T,20.9267,4,1.4717,...,0.7558,0,4,20.9267,Active,G,0,0,3,0
976,4,12,2,17,366.0194,22.5066,T,20.9267,4,1.9843,...,0.4814,0,4,20.9267,Active,G,0,0,3,0
1035,4,12,2,18,388.6147,22.5953,T,20.9267,4,2.8200,...,0.6829,0,4,20.9267,Active,G,0,0,3,0
1096,4,12,2,19,410.6505,22.0358,T,20.9267,4,3.1043,...,1.1601,0,4,20.9267,Active,G,0,0,3,0
1157,4,12,2,20,432.3572,21.7067,T,20.9267,4,2.5798,...,1.2571,0,4,20.9267,Active,G,0,0,3,0
1218,4,12,2,21,454.0815,21.7243,T,20.9267,4,1.9205,...,0.9366,0,4,20.9267,Active,G,0,0,3,0
1276,4,12,2,22,476.2249,22.1434,T,20.9267,4,1.5031,...,0.8371,0,4,20.9267,Active,G,0,0,3,0
1335,4,12,2,23,498.4115,22.1866,T,20.9267,4,1.3099,...,0.5114,0,4,20.9267,Active,G,0,0,3,0
1391,4,12,2,24,520.7458,22.3343,T,20.9267,4,1.1891,...,0.5229,0,4,20.9267,Active,G,0,0,3,0
1448,4,12,2,25,543.1869,22.4411,T,20.9267,4,1.2127,...,0.4519,0,4,20.9267,Active,G,0,0,3,0
1504,4,12,2,26,565.6902,22.5033,T,20.9267,4,1.1109,...,0.4631,0,4,20.9267,Active,G,0,0,3,0
1562,4,12,2,27,588.2919,22.6017,T,20.9267,4,1.1548,...,0.6051,0,4,20.9267,Active,G,0,0,3,0
1617,4,12,2,28,610.9317,22.6398,T,20.9267,4,1.1199,...,0.4601,0,4,20.9267,Active,G,0,0,3,0
1674,4,12,2,29,633.6849,22.7532,T,20.9267,4,1.1731,...,0.4305,0,4,20.9267,Active,G,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7466,7,12,2,125,3079.8021,49.0484,T,20.9139,34,9.7601,...,0.6614,0,7,20.9139,Active,G,2,7C,3,50
7523,7,12,2,126,3101.7390,21.9369,T,20.9139,34,9.4980,...,0.8882,0,7,20.9139,Active,G,2,7C,3,50
7558,6,12,2,127,3123.4859,21.7469,T,20.9139,34,31.2449,...,0.4710,0,6,20.9139,Active,G,2,7C,3,50
7619,6,12,2,128,3145.3624,21.8765,T,20.9139,34,9.5433,...,0.5381,0,6,20.9139,Active,G,2,7C,3,50
7675,5,12,2,129,3167.4375,22.0751,T,20.9139,34,2.9960,...,0.7511,0,5,20.9139,Active,G,2,7C,3,50
7739,5,12,2,130,3189.2979,21.8604,T,20.9139,34,2.8724,...,0.7685,0,5,20.9139,Active,G,2,7C,3,50
7799,5,12,2,131,3211.2094,21.9115,T,20.9139,34,2.8550,...,0.6503,0,5,20.9139,Active,G,2,7C,3,50
7862,5,12,2,132,3233.1478,21.9384,T,20.9139,34,2.4627,...,0.5688,0,5,20.9139,Active,G,2,7C,3,50
7918,5,12,2,133,3255.0970,21.9492,T,20.9139,34,2.0243,...,0.4721,0,5,20.9139,Active,G,2,7C,3,50
7975,5,12,2,134,3277.4739,22.3769,T,20.9139,34,2.0630,...,0.4345,0,5,20.9139,Active,G,2,7C,3,50
8033,5,12,2,135,3299.7321,22.2582,T,20.9139,34,1.9026,...,0.1824,0,5,20.9139,Active,G,2,7C,3,50
8089,5,12,2,136,3322.5378,22.8057,T,20.9139,34,1.8846,...,0.2854,0,5,20.9139,Active,G,2,7C,3,50
8150,5,12,2,137,3345.0920,22.5542,T,20.9139,34,1.8106,...,0.2418,0,5,20.9139,Active,G,2,7C,3,50
8209,5,12,2,138,3367.7842,22.6922,T,20.9139,34,1.9357,...,0.3417,0,5,20.9139,Active,G,2,7C,3,50
8261,5,12,2,139,3390.5458,22.7616,T,20.9139,34,2.1777,...,0.4071,0,5,20.9139,Active,G,2,7C,3,50
8322,5,12,2,140,3412.9910,22.4452,T,20.9139,34,2.1530,...,0.6566,0,5,20.9139,Active,G,2,7C,3,50
8382,5,12,2,141,3435.1946,22.2036,T,20.9139,34,1.9040,...,0.4396,0,5,20.9139,Active,G,2,7C,3,50
8442,5,12,2,142,3457.7079,22.5133,T,20.9139,34,1.8883,...,0.3873,0,5,20.9139,Active,G,2,7C,3,50
8502,5,12,2,143,3480.2458,22.5379,T,20.9139,34,1.7820,...,0.3133,0,5,20.9139,Active,G,2,7C,3,50
8561,5,12,2,144,3502.8284,22.5826,T,20.9139,34,1.4904,...,0.1790,0,5,20.9139,Active,G,2,7C,3,50
8619,5,12,2,145,3525.4771,22.6487,T,20.9139,34,1.2957,...,0.2237,0,5,20.9139,Active,G,2,7C,3,50
8674,5,12,2,146,3548.4597,22.9826,T,20.9139,34,1.5859,...,0.3640,0,5,20.9139,Active,G,2,7C,3,50
8730,5,12,2,147,3571.2153,22.7556,T,20.9139,34,1.5730,...,0.3265,0,5,20.9139,Active,G,2,7C,3,50
8783,5,12,2,148,3593.8705,22.6552,T,20.9139,34,1.5592,...,0.2981,0,5,20.9139,Active,G,2,7C,3,50
8839,5,12,2,149,3616.8972,23.0267,T,20.9139,34,1.3937,...,0.2296,0,5,20.9139,Active,G,2,7C,3,50
8896,5,12,2,150,3640.0374,23.1402,T,20.9139,34,1.9328,...,0.2456,0,5,20.9139,Active,G,2,7C,3,50
8948,4,12,2,151,3662.5667,22.5293,T,20.9139,34,1.6755,...,0.7796,0,4,20.9139,Active,G,2,7C,3,50
9008,4,12,2,152,3685.0714,22.5047,T,20.9139,34,1.5256,...,0.5859,0,4,20.9139,Active,G,2,7C,3,50
9134,16,12,2,153,3732.6153,47.5439,P,20.9139,34,3.5042,...,0.2539,0,10,20.9139,Active,G,3,99,3,50
9703,22,12,2,154,3964.5179,231.9026,P,20.9139,34,6.2467,...,20.3292,0,16,20.9139,Contact,G,4,9A,3,50

In [15]:
set(rankdata[rankdata['car_number']==12]['last_pitted_lap'])

{'0', '2B', '7C', '99', '9A'}

### pitstop analysis

In [16]:
def get_distance_data(car_number):
    """
    events_laplen = [1.022,2.5,1.5,0.894,2.5,1.25]
    """
    car = stintdf[stintdf['car_number']==car_number]
    
    normal_pits = car[car['pit_in_caution']==0]['eventid','lap_distance']
    
    
    caution_pits = car[car['pit_in_caution']==1]

In [17]:
events_laplen = [1.022,2.5,1.5,0.894,2.5,1.25]
car12 = stintdf[stintdf['car_number']==12]
car12

,lap_distance,start_lap,pit_lap,eventid,car_number,stageid,pit_in_caution,start_position,start_rank,end_rank
23,44,0,43,0,12,0,1,3,3,4
24,82,43,124,0,12,1,0,3,4,3
25,30,124,153,0,12,2,0,3,3,16

In [18]:
stintdf[stintdf['car_number']==15]

,lap_distance,start_lap,pit_lap,eventid,car_number,stageid,pit_in_caution,start_position,start_rank,end_rank
30,44,0,43,0,15,0,1,12,12,19
31,86,43,128,0,15,1,0,12,19,1
32,61,128,188,0,15,2,0,12,1,2
33,45,188,232,0,15,3,1,12,2,11

In [19]:
normal_pits = car12[car12['pit_in_caution']==0]
normal_pits
data = normal_pits[['eventid','lap_distance']].to_numpy()
data

array([[0, 82],
       [0, 30]], dtype=object)

In [20]:
data = normal_pits[['eventid','lap_distance']].to_numpy()
[events_laplen[x[0]]*x[1] for x in data]

[83.804, 30.66]

In [21]:
for event in stagedata.keys():
    print event

Phoenix